# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: 'mySecrets'
- name: 'secret'
  value: 'Name'
- name: 'nonsec'
  value: 'NonSecret'
pool:
  vmImage: 'ubuntu-18.04'


steps:
  - script: |
      echo $(secret)
      echo $(nonsec)

    env:
      MY_NAME: $(secret)
   
