e# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: 'mySecrets'
- name: 'secret'
  value: $[variables.Name]
- name: 'nonsec'
  value: $[variables.NonSecret]
pool:
  vmImage: 'ubuntu-18.04'

extends:
  temaplate: parameters.yml

steps:
  - script: |
      echo $(secret)
      echo $(nonsec)
      echo $(MY_NAME)

    env:
      MY_NAME: $(secret)
   
